### ISSUE TITLE
How to generate constituency_tree_encoding from ZPar

### ISSUE THREAD

**Issue by tungngthanh** [ExplorerFreda/TreeEnc#1]
I already tried to  use ZPar to generate the constituent tree like the following
(S (S (NP (PRP it)) (VP (VBZ &apos))) (: ;) (S (NP (NNS s)) (NP (IN that) (NN pyramid))) (. .))
How to generate constituency_tree_encoding  from this tree structure output ?

**Comment by ExplorerFreda** [comment]
Hello,

Disregarding that "& apos;" in your sentence should come from some HTML file, which might be better with some preprocess, you would probably need the following step:
1. Binarize the tree. The tool should be provided by Zpar, or some Zpar extensions -- actually I got it from my coauthor. If you had any problem on finding that, feel free to contact me and I can send you a copy of the tool. 
2. Remove all POS tags. Tip: In a string generated by Zpar, every item after each left parenthesis is a POS tag, which we would like to remove. 
3. Remove all redundant parenthesis, i.e., remove all unary branch of the tree. This should be easy to implement by a stack.  
4. Generate the constituency tree encoding following my instruction. 

Best,
Freda

**Comment by tungngthanh** [comment]
Thank you for quick reply. Appreciate it  a lot.
For the first 3 steps i  can do it my self. 
1. I binarize the tree by using Chomsky from nltk. However, if you can send me the tool then it is better as it is consistent with ZPar then i can reproduce results better.
2-3. We just remove the, i think that is problem of Stanford parser that keep generating a lot of redundant things
So i assume that we can get the following string to present tree, it is binary and does not have POS tags and redundant parenthesis:

> (S (S  it &apos) (S s (NP that pyramid)))

Then can you give me more details or the codes to generate the constituency tree encoding ? As you instruction i can see the we need to have the (left_i, right_i, parent_i,..) but i am not sure on how to do it, as how can we generate the first triple (left, right, parent) when we have a balance constituent tree like this:

> (S (S  (NP this place) &apos) (S s (NP that pyramid)))

Thank you for your time

**Comment by ExplorerFreda** [comment]
Sure! Actually I found my previous code below. It was really ugly thus I didn't include it into the repo -- I should probably work on it! 
The function takes a string of cleaned binary parse tree, and outputs the desired encoding.

```Python
def get_tree_encodings(binary_parse):
    binary_parse = binary_parse.replace('(', ' ( ').replace(')', ' ) ')
    sentence = binary_parse.replace('(', ' ').replace(')', ' ')
    words = sentence.split()
    components = binary_parse.split()
    final_answers = list()
    stack = list()
    curr_index = 0
    non_leaf_index = len(words)
    for w in components:
        if w == '(':  # guard
            stack.append(w)
        elif w != ')':  # shift
            stack.append(curr_index)
            curr_index += 1
        else:  # reduce
            index_left = stack[-2]
            index_right = stack[-1]
            final_answers.append(index_left)
            final_answers.append(index_right)
            final_answers.append(non_leaf_index)
            stack = stack[:len(stack)-3]
            stack.append(non_leaf_index)
            non_leaf_index += 1
    assert len(stack) == 1
    assert stack[0] == 2 * curr_index - 2
    assert curr_index == len(words)
    final_answers = [str(x) for x in final_answers]
    return ','.join(final_answers)
```

As for the tool from Zpar (maybe some Zpar extension), I think it shouldn't differ a lot with the default NLTK Chomsky normal form. Could you leave an email address if you would like it?

**Comment by tungngthanh** [comment]
Thank you for quick reply. The deadline is crazy so i do not have chance to reply sooner.
It would be great if you can send me the code. My email address is daitavuong92@gmail.com

**Comment by ExplorerFreda** [comment]
Sent an email to you, and I'll update the tree encoding function soon.

**Comment by Shajiu** [comment]
作者您好！请问您正对这个句法树得到后编码的程序存在一些问题呀：比如您可以用这句话“((((libertarians have) joined)(((environmental groups) (in (lobbying to))) (allow government))) ((((to use) ((the little) boxes)) ((to keep) (track of))) (((((the miles) you) (drive (, and))) (((possibly (where you)) drive) ((them ) then))) ((use (the information)) (((to draw) up) (a (tax (bill .))))))))”测试进行编码是出现bug.您有其他工具么？方便发我么？18810979033@163.com

**Comment by ExplorerFreda** [comment]
> 作者您好！请问您正对这个句法树得到后编码的程序存在一些问题呀：比如您可以用这句话“((((libertarians have) joined)(((environmental groups) (in (lobbying to))) (allow government))) ((((to use) ((the little) boxes)) ((to keep) (track of))) (((((the miles) you) (drive (, and))) (((possibly (where you)) drive) ((them ) then))) ((use (the information)) (((to draw) up) (a (tax (bill .))))))))”测试进行编码是出现bug.您有其他工具么？方便发我么？[18810979033@163.com](mailto:18810979033@163.com)

There's no bug in the code above -- it requires the tree to be completely binary, no unary branch, no n-ary branch (n>2). In contrast, you can see that in your tree, there's a subtree ((them ) then). The reason might be that some weird characters are treated as white spaces by some programs but not by others. 

Just for your information, it would be good if you could provide simpler examples. A good way to do so would be dividing the sentence into two halves and see if the "bug" remains for either one half; keep dividing and testing until you find the "bug".

**Comment by Shajiu** [comment]
作者您好！您的程序只能应用于dbpedia数据、不能应用于mt了是吧！因为我在运行mn数据时，出现一些问题，例如文件data.py中的函数def _convert_obj(self, obj):中sentence = obj['sentence']，这里获取的是源句子还是目标句子呀？obj['label']这个没有叭！方便加微信么？sj18810979033

**Comment by ExplorerFreda** [comment]
> 作者您好！您的程序只能应用于dbpedia数据、不能应用于mt了是吧！因为我在运行mn数据时，出现一些问题，例如文件data.py中的函数def _convert_obj(self, obj):中sentence = obj['sentence']，这里获取的是源句子还是目标句子呀？obj['label']这个没有叭！方便加微信么？sj18810979033

You can refer to the example data in the data/ folder---I think it's clear enough to address your questions.

**Comment by Shajiu** [comment]
感谢您呀！我已经正确处理完毕，最后想跟你请教一个问题就是，mn的词汇表中一个词为一行是吧！

在 2019-11-13 17:31:44，"Freda Shi" <notifications@github.com> 写道：


作者您好！您的程序只能应用于dbpedia数据、不能应用于mt了是吧！因为我在运行mn数据时，出现一些问题，例如文件data.py中的函数def _convert_obj(self, obj):中sentence = obj['sentence']，这里获取的是源句子还是目标句子呀？obj['label']这个没有叭！方便加微信么？sj18810979033

You can refer to the example data in the data/ folder---I think it's clear enough to address your questions.

**Comment by Shajiu** [comment]
作者您好！我训练翻译数据时，在代码TreeEnc-master/src/data.py", line 395, ：
items = [int(x) for x in tree_encoding.strip().split(',')]
        print()
        sentence_length = len(items) // 3 + 1
        curr_sent = [x for x in range(sentence_length)]
        mask_ids = list()
        
        assert 3 * (sentence_length - 1) == len(items)
这个地方为啥时整除3呢？
我的句子tree_encoding=“0,1,41,41,2,42,3,4,43,6,7,44,5,44,45,43,45,46,8,9,47,46,47,48,42,48,49,10,11,50,12,13,51,51,14,52,50,52,53,15,16,54,17,18,55,54,55,56,53,56,57,19,20,58,58,21,59,23,24,60,22,60,61,59,61,62,26,27,63,25,63,64,64,28,65,29,66,66,30,67,67,68,68,69,32,33,70,31,70,71,34,35,72,72,36,73,39,40,74,38,74,75,37,75,76,73,76,77,71,77,78,69,78,79,79,80,80,81”
时，assert 3 * (sentence_length - 1) == len(items)，前后不一致，117和118那这个怎么会时呢？

**Comment by Shajiu** [comment]
方便加您微信详细聊么？
