### ISSUE TITLE
标签

### ISSUE THREAD

**Issue by Shajiu** [ExplorerFreda/TreeEnc#3]
作者您好！您的数据集中给定的"label": 有什么规定么？这是怎么获取到的？然后又是怎么添加的呢？

**Comment by ExplorerFreda** [comment]
The "label" field only applies for classification tasks. You can 
1. download a dataset (see paper for further reference) for classification -- each instance should have a label;  
2. make a label vocabulary, to match each label to an integer; 
3. put the integer corresponding to the label into the processed .json dataset.
